version: '2'
services:
    jhipstertrial-app:
        image: jhipstertrial
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstertrial-postgresql:5432/jhipsterTrial
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstertrial-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstertrial-postgresql
