version: '2'
services:
    jhipstertrial-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/jhipsterTrial/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterTrial
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
